name: Auto-add to Project Board

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
      - name: Add to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/wyre-technology/projects/1
          github-token: ${{ secrets.GATEWAY_DISPATCH_TOKEN }}
